#!/usr/bin/env php
<?php

// Check if --dev is passed
$dev = in_array('--dev', $argv);
if ($dev) {
    // Remove it so it doesn't get passed to Artisan
    unset($argv[array_search('--dev', $argv)]);
}

// Create .env if needed
if (! file_exists(__DIR__.'/.env')) {
    $example = $dev ? '.env.example' : '.env.production.example';
    copy(__DIR__. '/' . $example . '', __DIR__.'/.env');
}

// Run Composer install if needed
if (! file_exists(__DIR__.'/vendor/autoload.php')) {
    passthru('composer install --no-dev', $composerResultCode);

    // If something failed, we stop
    if (! $composerResultCode) {
        exit($composerResultCode);
    }
}

// Now we can run the Artisan install command
passthru('php artisan app:install --ansi', $artisanResultCode);

// If something failed, we write a message to the user
if ($artisanResultCode !== 0) {
    echo 'Installation failed. Please check the logs above for more information, then run the installer again.';
}

exit($artisanResultCode);
